database:
  host: ${DB_GREEN_HOST:mysql-green}
  port: ${DB_GREEN_PORT:3307}
  name: ${DB_NAME:legal_data}
  user: ${DB_USER:root}
  password: ${DB_PASSWORD:password}
  charset: utf8mb4
  
connection_pool:
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

mysql_settings:
  sql_mode: "STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
  time_zone: "+09:00"
  innodb_buffer_pool_size: "1G"