# Prometheus 설정 파일
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'legal-data-pipeline'
    region: 'local'

# 규칙 파일 로딩
rule_files:
  # - "rules/*.yml"

# 스크랩 설정
scrape_configs:
  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX 메트릭
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka1:19092', 'kafka2:19093', 'kafka3:19094']
    metrics_path: /metrics
    scrape_interval: 30s

  # MySQL 메트릭 (Blue/Green)
  - job_name: 'mysql-blue'
    static_configs:
      - targets: ['mysql-blue:3306']
    scrape_interval: 30s
    
  - job_name: 'mysql-green'
    static_configs:
      - targets: ['mysql-green:3306']
    scrape_interval: 30s

  # Redis 메트릭
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Zookeeper 메트릭
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']
    scrape_interval: 30s

  # Schema Registry 메트릭
  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:8081']
    scrape_interval: 30s
    metrics_path: /metrics

  # 애플리케이션 메트릭 (나중에 추가)
  # - job_name: 'legal-api-server'
  #   static_configs:
  #     - targets: ['legal-api:8000']
  #   scrape_interval: 15s

  # - job_name: 'legal-data-producer'
  #   static_configs:
  #     - targets: ['legal-producer:8001']
  #   scrape_interval: 15s

  # - job_name: 'legal-data-consumer'
  #   static_configs:
  #     - targets: ['legal-consumer:8002']
  #   scrape_interval: 15s

# 알림 설정
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# 원격 쓰기/읽기 설정 (선택사항)
# remote_write:
#   - url: "http://remote-storage:9090/api/v1/write"

# remote_read:
#   - url: "http://remote-storage:9090/api/v1/read"
